Cigarette_Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Main_App.urls')),
    path('Domestic_Cigarette/', include('Domestic_Cigarette_App.urls')),
    path('Foreign_Cigarette/', include('Foreign_Cigarette_App.urls')),
    path('Member/', include('Member_App.urls')),
]

Main_App/urls.py
from django.urls import path, include
from . import views

app_name = 'Main_App'

urlpatterns = [
    path('', views.readMainPage, name='RMP')
]

Member_App/urls.py
from django.urls import path
from . import views

app_name = 'Member_App'

urlpatterns = [
    path('signUp/', views.signUp, name='SU'),
    path('idCheck/', views.idCheck, name='IC'),
    path('signUpFinish/', views.signUpFinish, name='SUF'),
    path('logIn/', views.logIn, name='LI'),
    path('logOut/', views.logOut, name='LO'),
]

Member_App/models.py
from django.db import models

# Create your models here.

Member_App/views.py
import json
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib import auth

# Create your views here.
def signUp(request) :
  if request.method == "POST" :
    username = request.POST.get('username')
    email = request.POST.get('email')
    password1 = request.POST.get('password1')
    password2 = request.POST.get('password2')
    
    user = User.objects.create_user(username=username, email=email, password=password1)
    return HttpResponseRedirect(reverse('Member_App:SUF'))
    
  return render(request, 'Member_App/signUp.html')
  

def idCheck(request) :
  input_id = request.GET.get('input_id')
  try :
    user = User.objects.get(username=input_id)
  except :
    user = None
  
  if user is None :
    response = "success"
  else :
    response = "fail"
  
  context = {'response' : response}
  return JsonResponse(context)
  

def signUpFinish(request) :
  return render(request, 'Member_App/signUpFinish.html')
  

def logIn(request) :
  redirect_url = request.GET.get('next')
  if(redirect_url is None or "Member" in redirect_url) :
    redirect_url = '/'
    
  if request.is_ajax() :
    input_username = request.POST.get('username')
    input_password = request.POST.get('password')
    user = auth.authenticate(request, username=input_username, password=input_password)
    
    if user is not None :
      response = "success"
      auth.login(request, user)
    else :
      response = "fail"
    
    context = {'response' : response, 'redirect_url' : redirect_url}
    return JsonResponse(context)
  
  context = {'redirect_url' : redirect_url}      
  return render(request, 'Member_App/logIn.html', context)
  

def logOut(request) :
  redirect_url = request.GET.get('next')
  if(redirect_url is None or "Member" in redirect_url) :
    redirect_url = '/'
    
  if request.user.is_authenticated :
    auth.logout(request)
    return HttpResponseRedirect(redirect_url)
    
  return HttpResponseRedirect(reverse('Main_App:RMP'))

Member_App/templates/Member_App/logIn.html
{% extends "base.html" %}

{% load static %}

{% block scripts %}
<script>
        // using jQuery
        function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
            }
        }
        return cookieValue;
        }
        function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        $(document).ready(function() {
        var csrftoken = getCookie('csrftoken');
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
            }
        });
        
        var frm = $('#logIn_form');
        frm.submit(function(e){
            var input_id = $('#username_input').val();
            var input_password = $('#password_input').val();
            
            if(input_id == ''){
                alert('아이디를 입력해주십시오.');
                return false;
            }
            if(input_password == ''){
                alert('비밀번호를 입력하여 주십시오.');
                return false;
            }
            
            e.preventDefault();
        
            $.ajax({
                url : frm.attr('action'),
                type : frm.attr('method'),
                data : frm.serialize(),
                dataType : 'json',
                success : function(data) {
                    if(data['response'] == "fail"){
                        alert("Id or Password Not Exists");
                        $('#username_input').focus();		             		             
                    } else {
                        alert("LogIn Success");
                        window.location.href=data['redirect_url'];                        		                 		             		                		                 
                    }		             
                },
                error : function(error){
                    alert(error);
                }
            });
          });
        });        
</script>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/base_css.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    {% if user.is_authenticated %}
    <h1>이미 로그인이 되어있습니다.</h1>
    {% else %}
    <form id="logIn_form" action="{% url 'Member_App:LI' %}?next={{redirect_url}}" method="POST">
        {% csrf_token %}
        <table>
            <tr>
                <td>아이디(닉네임)</td>
                <td><input id="username_input" type="text" name="username"></td>
            </tr>
            <tr>
                <td>비밀번호</td>
                <td><input id="password_input" type="password" name="password"></td>
            </tr>
        </table>
        <input type="submit" value="로그인하기">
    </form>                
    {% endif %}
</div>
{% endblock %}

Member_App/templates/Member_App/signUp.html
{% extends "base.html" %}

{% load static %}

{% block scripts %}
<script>
    $(document).ready(function(){
        $('#username_input').change(function(){
            $('#id_success').hide();
            $('#button_idCheck').show();
            $('#username_input').attr("check" , "fail");
        });
        
        $('#button_idCheck').click(function(){
            var input_id = $('#username_input').val();
            if(input_id == ''){
                alert('아이디를 입력해주십시오.');
                return;
            }
        
        $.ajax({
            url : "{% url 'Member_App:IC' %}",
            data : { 'input_id' : input_id },
            dataType : 'json',
            success : function(data) {
                if(data['response'] == "fail"){
                    alert("already existed");
                    $('#username_input').focus();
                    return;
                } else {
                    alert("can use");
                    $('#username_input').attr("check" , "success");
                    $('#id_success').show();
                    $('#button_idCheck').hide();
                    return;		                 
                }
            }
          });
        });
        
        $('#signUp_form').submit(function(){
            if($('#username_input').attr("check") == "fail"){
                alert("ID Check Please");
                $('#username_input').focus();
                return false;
            }
            
            if($('#password1').val() != $('#password2').val()){
                alert("Password Wrong");
                $('#password1').focus();
                return false;
            }
        });
    });
</script>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/base_css.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <h2>회원가입</h2>
    <form id="signUp_form" action="{% url 'Member_App:SU' %}" method="POST">
        {% csrf_token %}
        <table>
            <tr>
                <td>아이디 및 닉네임</td>
                <td><input type="text" id="username_input" name="username" check="fail"></td>
                <td><button type="button" id="button_idCheck">중복 확인하기</button><span id="id_success" style="display:none;">V</span></td>
            </tr>
            <tr>
                <td>이메일</td>
                <td><input type="text" name="email"></td>
            </tr>
            <tr>
                <td>비밀번호</td>
                <td><input id="password1" type="password" name="password1"></td>
            </tr>
            <tr>
                <td>비밀번호 재입력</td>
                <td><input id="password2" type="password" name="password2"></td>
            </tr>
        </table>
        <input type="submit" value="가입하기">
    </form>
</div>
{% endblock %}

Member_App/templates/Member_App/signUpFinish.html
{% extends "base.html" %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/base_css.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <h2>회원가입 성공</h2>
    <a href="{% url 'Member_App:LI' %}">로그인 하기</a>
</div>
{% endblock %}