Cigarette_Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Main_App.urls')),
    path('Domestic_Cigarette/', include('Domestic_Cigarette_App.urls')),
    path('Foreign_Cigarette/', include('Foreign_Cigarette_App.urls')),
    path('Member/', include('Member_App.urls')),
]

Domestic_Cigarette_App/urls.py
from django.urls import path
from . import views

app_name = 'Domestic_Cigarette_App'

urlpatterns = [
    path('all/', views.readCigaretteAll, name='RCA'),
    path('<str:category>/', views.readCigaretteCategory, name='RCC'),
    path('<str:name>/detail/', views.readCigaretteDetail, name='RCD'),
    path('<int:item_pk>/detail/createComment/', views.createNewComment, name='CNC'),
    path('<int:item_pk>/detail/deleteComment/', views.deleteComment, name='DC'),
]

Main_App/urls.py
from django.urls import path, include
from . import views

app_name = 'Main_App'

urlpatterns = [
    path('', views.readMainPage, name='RMP')
]

Member_App/urls.py
from django.urls import path
from . import views

app_name = 'Member_App'

urlpatterns = [
    path('signUp/', views.signUp, name='SU'),
    path('idCheck/', views.idCheck, name='IC'),
    path('signUpFinish/', views.signUpFinish, name='SUF'),
    path('logIn/', views.logIn, name='LI'),
    path('logOut/', views.logOut, name='LO'),
]

Domestic_Cigarette_App/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse

# Create your models here.
class Domestic_Cigarette_Category(models.Model) :
  Category = models.CharField(max_length=100)
  
  def __str__(self) :
    return self.Category
    
    
class Domestic_Cigarette(models.Model) :
  Category = models.CharField(max_length=100)
  Name = models.CharField(max_length=100)
  Price = models.IntegerField(default=0)
  Tar = models.DecimalField(default=0, max_digits=2, decimal_places=1)
  Nicotine = models.DecimalField(default=0, max_digits=3, decimal_places=2)
  StarPoints = models.PositiveIntegerField(default=0)
  StarPoint = models.DecimalField(default=0, max_digits=2, decimal_places=1)
  
  def __str__(self) :
    return self.Name
    
  def get_absolute_url(self) :
    return reverse('Domestic_Cigarette_App:RCD', args=[self.Name])
    
  def StarPointUpdate(self, StarPoint) :
    self.StarPoints += StarPoint
    self.StarPoint = self.StarPoints / self.Comments.count()
    self.save()
  
  def StarPointDelete(self, StarPoint) :
    self.StarPoints -= StarPoint
    if(self.Comments.count() - 1 <= 0) :
      self.StarPoint = 0
    else :
      self.StarPoint = self.StarPoints / (self.Comments.count() - 1)
    self.save() 
    
    
class Domestic_Cigarette_Comment(models.Model) :
  Object = models.ForeignKey(Domestic_Cigarette, on_delete=models.CASCADE, related_name='Comments')
  Nickname = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='D_Nickname')
  Content = models.CharField(max_length=100)
  StarPoint = models.PositiveSmallIntegerField(default=0)
  
  def __str__(self) :
    return self.Nickname.username
    

Domestic_Cigarette_App/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render, get_object_or_404, resolve_url
from Domestic_Cigarette_App.models import Domestic_Cigarette, Domestic_Cigarette_Category, Domestic_Cigarette_Comment
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib.auth import get_user_model

# Create your views here.
def readCigaretteAll(request) :
  category_query_set = Domestic_Cigarette_Category.objects.all()
  list_query_set = Domestic_Cigarette.objects.all()
    
  context = {'cigarette_category' : category_query_set, 'cigarette_list' : list_query_set}
  return render(request, 'Domestic_Cigarette_App/readCigaretteAll.html', context)
  
  
def readCigaretteCategory(request, category) :
  selected_category = category
  category_query_set = Domestic_Cigarette_Category.objects.all()
  list_query_set = Domestic_Cigarette.objects.filter(Category=category)
  
  context = {'selected_category' : selected_category, 'cigarette_category' : category_query_set, 'cigarette_list' : list_query_set}
  return render(request, 'Domestic_Cigarette_App/readCigaretteCategory.html', context)
  
  
def readCigaretteDetail(request, name) :
  item_query_set = Domestic_Cigarette.objects.get(Name=name)
  
  context = {'selected_item' : item_query_set}
  return render(request, 'Domestic_Cigarette_App/readCigaretteDetail.html', context)
  

@login_required 
def createNewComment(request, item_pk) :
  if request.method == "POST" :
    Nickname_pk = int(request.POST.get('Nickname'))
    
    Object = get_object_or_404(Domestic_Cigarette, pk=item_pk)
    Nickname = get_object_or_404(get_user_model(), pk=Nickname_pk)
    Content = request.POST.get('Content')
    StarPoint = request.POST.get('StarPoint')
  
    Domestic_Cigarette_Comment.objects.create(Object=Object, Nickname=Nickname, Content=Content, StarPoint=StarPoint)
    StarPoint = int(StarPoint)
    Object.StarPointUpdate(StarPoint)
    
  return HttpResponseRedirect(resolve_url(Object))
  
  
@login_required
def deleteComment(request, item_pk) :
  Comment = get_object_or_404(Domestic_Cigarette_Comment, pk=item_pk)
  Object = Comment.Object
  
  if Comment.Nickname.username == request.user.username :
    StarPoint = Comment.StarPoint
    Object.StarPointDelete(StarPoint)
    Comment.delete()
    
  return HttpResponseRedirect(resolve_url(Object))

Domestic_Cigarette_App/templates/Domestic_Cigarette_App/readCigaretteAll.html
{% extends "base.html" %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/base_css.css' %}">
<link rel="stylesheet" href="{% static 'css/readCigarette_css.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <div class="navigation">
        {% if cigarette_category %}
        <ul>
            <li><a href="{% url 'Domestic_Cigarette_App:RCA' %}" style="background:red;">ALL</a></li>
            {% for item in cigarette_category %}
            <li><a href="{% url 'Domestic_Cigarette_App:RCC' item.Category %}">{{item.Category}}</a></li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
</div>
    
<div class="container">
    {% if cigarette_list %}
    <div class="cigarette-list">
        {% for item in cigarette_list %}
        <li>
            <div class="image">
                <a href="{% url 'Domestic_Cigarette_App:RCD' item.Name %}"><img src="http://placehold.it/150x200" width="150" height="200"></a>
            </div>
            <div class="cigainfo">
                <p class="name"><a href="{% url 'Domestic_Cigarette_App:RCD' item.Name %}">{{item.Name}}</a></p>
                <p class="price">{{item.Price}}Won</p>
                <p class="good">SP : {{item.StarPoint}}</p>
                <p>( {{item.Comments.count}} )</p>
            </div>
        </li>
        {% endfor %}
    </div>
    {% else %}
    <h3>This Post Does Not Exist.</h3>
    {% endif %}
</div>
{% endblock %}

Domestic_Cigarette_App/templates/Domestic_Cigarette_App/readCigaretteCategory.html
{% extends "base.html" %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/base_css.css' %}">
<link rel="stylesheet" href="{% static 'css/readCigarette_css.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <div class="navigation">
        {% if cigarette_category %}
        <ul>
            <li><a href="{% url 'Domestic_Cigarette_App:RCA' %}">ALL</a></li>
            {% for item in cigarette_category %}
                {% if item.Category == selected_category %}
                <li><a href="{% url 'Domestic_Cigarette_App:RCC' item.Category %}" style="background:red;">{{item.Category}}</a></li>
                {% else %}
                <li><a href="{% url 'Domestic_Cigarette_App:RCC' item.Category %}">{{item.Category}}</a></li>
                {% endif %}
            {% endfor %}
        </ul>
        {% endif %}
    </div>
</div>
    
<div class="container">
    {% if cigarette_list %}
    <div class="cigarette-list">
        {% for item in cigarette_list %}
        <li>
            <div class="image">
                <a href="{% url 'Domestic_Cigarette_App:RCD' item.Name %}"><img src="http://placehold.it/150x200" width="150" height="200"></a>
            </div>
            <div class="cigainfo">
                <p class="name"><a href="{% url 'Domestic_Cigarette_App:RCD' item.Name %}">{{item.Name}}</a></p>
                <p class="price">{{item.Price}}Won</p>
                <p class="good">SP : {{item.StarPoint}}</p>
                <p>( {{item.Comments.count}} )</p>
            </div>
        </li>
        {% endfor %}
    </div>
    {% else %}
    <h3>This Post Does Not Exist.</h3>
    {% endif %}
</div>
{% endblock %}

Domestic_Cigarette_App/templates/Domestic_Cigarette_App/readCigaretteDetail.html
{% extends "base.html" %}

{% load static %}

{% block scripts %}
<script src="/static/js/readCigaretteDetail_js.js"></script>
<script>
    $(document).ready(function(){
        $('#createChat').click(function(){
            var a = "{{request.user.is_authenticated}}";
            if(a=="True"){
                $('#newComment').toggle();
            }
            else{
                if(confirm("댓글을 작성하려면 로그인을 해야합니다.") == true){
                    window.location.href="{% url 'Member_App:LI' %}?next={{request.path}}";
                }
                else{
                    return;
                }
            }
        });
    });
</script>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/base_css.css' %}">
<link rel="stylesheet" href="{% static 'css/readCigaretteDetail_css.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <div class="left-image">
        <img src="http://placehold.it/300x300" width="300" height="300">
    </div>
    <div class="information">
        <h1>{{selected_item.Name}}</h1>
        <hr>
        <br>
        <table>
            <tr height="50px">
                <th>
                    <h3>타르 : </h3>
                </th>
                <td>
                    <h3>{{selected_item.Tar}} mg</h3>
                </td>
            </tr>
            <tr height="50px">
                <th>
                    <h3>니코틴 : </h3>
                </th>
                <td>
                    <h3>{{selected_item.Nicotine}} mg</h3>
                </td>
            </tr>
            <tr height="50px">
                <th>
                    <h3>별점 : </h3>
                </th>
                <td>
                    <h3>{{selected_item.StarPoint}} Points</h3>
                </td>
            </tr>
            <tr height="50px">
                <th>
                    <h3>가격 : </h3>
                </th>
                <td>
                    <h3>{{selected_item.Price}} 원</h3>
                </td>
            </tr>
        </table>
    </div>
</div>

<div class="container">
    <div class="goodandbad">
        <span id="Gnum">0</span>
        <button id="good">좋아요
        </button>      
        <button id="bad">별로에요
        </button>
        <span id="Bnum">0</span>
    </div>
</div>


<div class="container">
    <div class="chatInfo">
        <h1 id="commentNum">{{selected_item.Comments.count}} 개의 댓글</h1>
        <button id="createChat"type="button">댓글 쓰기</button>
    </div>
    <div class="comment" id="newComment">
        <form action="{% url 'Domestic_Cigarette_App:CNC' item_pk=selected_item.pk %}" method="POST">
            {% csrf_token %}
            <p id="star_grade">
                <span>StarPoint : </span>
                <a href="#" value="1">★</a>
                <a href="#" value="2">★</a>
                <a href="#" value="3">★</a>
                <a href="#" value="4">★</a>
                <a href="#" value="5">★</a>
            </p>
            <input type="hidden" name="StarPoint" id="starPoint" value="0">
            <p>{{user.username}}</p>
            <input type="hidden" name="Nickname" value="{{user.pk}}">
            <textarea cols="140" rows="3" name="Content" placeholder="내용"></textarea>
            <button type="submit">등록</button>
        </form>
    </div>
    <div class="comment">
        <div class="chat_data">
            {% for item in selected_item.Comments.all %}
            <div>
                <p>{{item.Nickname.username}}&nbsp;&nbsp;&nbsp;{{item.StarPoint}} Points</p>
                <h5>{{item.Content}}</h5>
                <p class="EditAndDelete" value="{{item.Nickname.username}}">
                    <a href="">수정</a>
                    <a href="{% url 'Domestic_Cigarette_App:DC' item_pk=item.pk %}" class="deleteBtn">삭제</a>
                </p>
                <hr>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}