Cigarette_Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Main_App.urls')),
    path('Domestic_Cigarette/', include('Domestic_Cigarette_App.urls')),
    path('Foreign_Cigarette/', include('Foreign_Cigarette_App.urls')),
    path('Member/', include('Member_App.urls')),
]

Main_App/urls.py
from django.urls import path, include
from . import views

app_name = 'Main_App'

urlpatterns = [
    path('', views.readMainPage, name='RMP')
]

Member_App/urls.py
from django.urls import path
from . import views

app_name = 'Member_App'

urlpatterns = [
    path('signUp/', views.signUp, name='SU'),
    path('idCheck/', views.idCheck, name='IC'),
    path('signUpFinish/', views.signUpFinish, name='SUF'),
    path('logIn/', views.logIn, name='LI'),
    path('logOut/', views.logOut, name='LO'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <script src="http://code.jquery.com/jquery-3.4.1.js"></script>
        {% block scripts %}
        {% endblock %}
        {% block css %}
        {% endblock %}
    </head>
    <body>
    	<div class="container">
    	    <div class="member">
    	    <span id="user_username">{{user.username}}</span>
    	    {% if request.user.is_authenticated %}
    	        <a href="{% url 'Member_App:LO' %}?next={{request.path}}">로그아웃</a>
    	    {% else %}
                <a href="{% url 'Member_App:SU' %}">회원가입</a>
                <a href="{% url 'Member_App:LI' %}?next={{request.path}}">로그인</a>
    	    {% endif %}
            </div>
        </div>
            
        <div class="container">
            <div class="top-container">
                <h1><a href="{% url 'Main_App:RMP' %}" title="꼴초">꼴초</a></h1>
                <button type="button" id="search">검색</button>
            </div>
        </div>
            
        {% block content %}
        {% endblock %}
    </body>
</html>